server:
  port: 80
  servlet:
    context-path: /boot

spring:
  profiles:
    active: dev
    # 激活外部的配置  application-test | application-dev
    # 外部配置的key和application key重复  外部的覆盖内部!!
    # jar  --active=test
  web:
    resources:
      static-locations: classpath:/webapp  #配置静态资源文件夹
      # 一旦你配置了默认的静态资源文件夹就无法访问了  static public resources META-INF/resources
      # 外部访问静态资源的时候，不需要写静态资源文件夹